CREATE TABLE [dbo].[CosCategoryMst] (
    [CatCode] VARCHAR (3)   NOT NULL,
    [CatName] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK__CosCateg__5E593E4F5E1FF51F] PRIMARY KEY CLUSTERED ([CatCode] ASC)
);

